[uwsgi]
socket = 127.0.0.1:4600
chdir = /home/ubuntu/www/SitioMTCRM/
wsgi-file = config/wsgi.py
processes = 4
threads = 2
stats = 127.0.0.1:9495
daemonize = /home/ubuntu/www/SitioMTCRM/log/uwsgi.log
pidfile = /home/ubuntu/www/SitioMTCRM/uwsgi.pid
plugin = python3
home = /home/ubuntu/DJENV/

; Serve static and media directly via uWSGI in production
#static-map = /static=/home/ubuntu/www/SitioMTCRM/staticfiles
#static-map = /media=/home/ubuntu/www/SitioMTCRM/media

; Optional: offload static serving to dedicated threads
offload-threads = 2
vacuum = true

; Prevent worker restarts (avoid session loss)
max-requests = 0
reload-on-rss = 0
harakiri = 300
harakiri-verbose = true

; Enable master mode for better process management
master = true

; Lazy apps to avoid loading before forking
lazy-apps = true
