# Generated by Django 4.2.16 on 2026-08-24 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='reportchangelog',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_changes', to=settings.AUTH_USER_MODEL, verbose_name='Revertido por'),
        ),
        migrations.AddField(
            model_name='reportchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='remito',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='remito',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='remito',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='profitreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='pricelistproduct',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='erp.pricelist', verbose_name='Lista de precios'),
        ),
        migrations.AddField(
            model_name='pricelistproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_config', to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='libroivaregistro',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='libroivaregistro',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.sale', verbose_name='Venta Relacionada'),
        ),
        migrations.AddField(
            model_name='libroivaregistro',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplier', verbose_name='Proveedor Relacionado'),
        ),
        migrations.AddField(
            model_name='internaltransferdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='internaltransferdetail',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='erp.internaltransfer', verbose_name='Transferencia'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='remito_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.remitoentrada', verbose_name='Remito de Entrada Relacionado'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='employeeaccountsale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='employeeaccountsale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='employeeaccountsale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
        migrations.AddField(
            model_name='detemployeeaccount',
            name='employee_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeeaccountsale'),
        ),
        migrations.AddField(
            model_name='detemployeeaccount',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detalleremitoentrada',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detalleremitoentrada',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.remitoentrada', verbose_name='Remito'),
        ),
        migrations.AddField(
            model_name='detalleremito',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detalleremito',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.remito', verbose_name='Remito'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.sale', verbose_name='Venta Relacionada'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='client',
            name='precio_lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.pricelist', verbose_name='Lista de precios'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='category',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogoconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='catalogoconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogo_configs', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.cashregister'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cardinstallmentplan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.sale', verbose_name='Venta Relacionada'),
        ),
        migrations.AddField(
            model_name='afippuntoventa',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salevatbreakdown',
            unique_together={('sale', 'vat_code')},
        ),
        migrations.AlterUniqueTogether(
            name='reportconfiguration',
            unique_together={('user', 'report_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['report_type', 'created_at'], name='erp_reportc_report__61c314_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['user', 'created_at'], name='erp_reportc_user_id_d8ee90_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['is_reverted'], name='erp_reportc_is_reve_ca5b86_idx'),
        ),
        migrations.AddIndex(
            model_name='profitreport',
            index=models.Index(fields=['company', 'date_from', 'date_to'], name='erp_profitr_company_82796e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistproduct',
            unique_together={('price_list', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='posterminal',
            unique_together={('company', 'number')},
        ),
        migrations.AddIndex(
            model_name='libroivaregistro',
            index=models.Index(fields=['company', 'tipo_registro', 'fecha'], name='erp_libroiv_company_bba9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='libroivaregistro',
            index=models.Index(fields=['fecha'], name='erp_libroiv_fecha_05d505_idx'),
        ),
        migrations.AddIndex(
            model_name='libroivaregistro',
            index=models.Index(fields=['cae'], name='erp_libroiv_cae_a4e90f_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedor',
            index=models.Index(fields=['company', 'supplier', 'fecha'], name='erp_factura_company_8535c8_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedor',
            index=models.Index(fields=['fecha'], name='erp_factura_fecha_749e02_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedor',
            index=models.Index(fields=['cae'], name='erp_factura_cae_2cd82f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['company', 'client', 'fecha'], name='erp_cuentac_company_44735d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['client', 'fecha'], name='erp_cuentac_client__012093_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['company', 'fecha'], name='erp_asiento_company_431d94_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['tipo_asiento', 'fecha'], name='erp_asiento_tipo_as_42573a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='afippuntoventa',
            unique_together={('company', 'numero')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='erp_activit_user_id_396f42_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='erp_activit_action_945d14_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['company', 'timestamp'], name='erp_activit_company_aa6378_idx'),
        ),
    ]
