# Generated by Django 5.0.6 on 2026-06-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.cashregister'),
        ),
        migrations.AddField(
            model_name='category',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='catalogoconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='employeeaccountsale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='employeeaccountsale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='detemployeeaccount',
            name='employee_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeeaccountsale'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='internaltransferdetail',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='erp.internaltransfer', verbose_name='Transferencia'),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_config', to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='internaltransferdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detemployeeaccount',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detalleremitoentrada',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='profitreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='detalleremitoentrada',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.remitoentrada', verbose_name='Remito'),
        ),
        migrations.AddField(
            model_name='reportchangelog',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_changes', to=settings.AUTH_USER_MODEL, verbose_name='Revertido por'),
        ),
        migrations.AddField(
            model_name='reportchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='erp_activit_user_id_396f42_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='erp_activit_action_945d14_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['company', 'timestamp'], name='erp_activit_company_aa6378_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posterminal',
            unique_together={('company', 'number')},
        ),
        migrations.AddIndex(
            model_name='profitreport',
            index=models.Index(fields=['company', 'date_from', 'date_to'], name='erp_profitr_company_82796e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['report_type', 'created_at'], name='erp_reportc_report__61c314_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['user', 'created_at'], name='erp_reportc_user_id_d8ee90_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangelog',
            index=models.Index(fields=['is_reverted'], name='erp_reportc_is_reve_ca5b86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportconfiguration',
            unique_together={('user', 'report_type', 'name')},
        ),
    ]
