# Generated by Django 5.0.6 on 2026-06-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportconfiguration',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportChangeLog',
        ),
        migrations.DeleteModel(
            name='ReportConfiguration',
        ),
    ]
