# Generated by Django 4.2.16 on 2026-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='local_uuid',
            field=models.CharField(blank=True, help_text='UUID para sincronización (unique para prevenir duplicados)', max_length=64, null=True, unique=True, verbose_name='UUID local'),
        ),
    ]
