# Generated by Django 5.0.6 on 2026-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='local_server_url',
            field=models.CharField(blank=True, help_text='URL del servidor local para sincronización (ej: http://192.168.1.100:8000)', max_length=255, null=True, verbose_name='URL del Servidor Local'),
        ),
        migrations.AddField(
            model_name='company',
            name='sync_destination',
            field=models.CharField(choices=[('cloud', 'Nube (Servidor Central)'), ('local', 'Servidor Local'), ('both', 'Ambos')], default='cloud', max_length=10, verbose_name='Destino de Sincronización'),
        ),
    ]
