# Generated by Django 4.2.16 on 2026-08-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_sale_local_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freight_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Flete (%)'),
        ),
    ]
