# Generated by Django 4.2.16 on 2026-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_add_freight_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstallmentplan',
            name='card_brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('maestro', 'Maestro')], default='visa', max_length=20, verbose_name='Marca de tarjeta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('maestro', 'Maestro'), ('other', 'Otra')], max_length=20, null=True, verbose_name='Marca de tarjeta'),
        ),
    ]
