# Generated by Django 4.2.16 on 2026-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_cardinstallmentplan_card_brand_alter_sale_card_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='remito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.remito', verbose_name='Remito Relacionado'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('facturado', 'Facturado'), ('cancelled', 'Anulado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
