# Generated by Django 4.2.16 on 2026-08-30 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0006_facturaproveedor_remito_alter_remito_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginAdjustmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje aplicado')),
                ('product_count', models.IntegerField(verbose_name='Productos afectados')),
                ('snapshot', models.JSONField(verbose_name='Snapshot de precios anteriores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('undone', models.BooleanField(default=False, verbose_name='Deshecho')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de Margen',
                'verbose_name_plural': 'Ajustes de Margen',
                'ordering': ['-created_at'],
            },
        ),
    ]
