# Generated by Django 4.2.16 on 2026-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_marginadjustmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='iva_incluido',
            field=models.BooleanField(default=False, verbose_name='IVA incluido en precio'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='iva_incluido',
            field=models.BooleanField(default=False, verbose_name='IVA incluido en precio'),
        ),
        migrations.AlterField(
            model_name='cardinstallmentplan',
            name='card_brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('maestro', 'Maestro'), ('cabal', 'Cabal'), ('otras', 'Otras')], default='visa', max_length=20, verbose_name='Marca de tarjeta'),
        ),
    ]
