# Generated by Django 4.2.16 on 2026-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_add_iva_incluido_to_remitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remito',
            name='iva_incluido',
        ),
        migrations.RemoveField(
            model_name='remitoentrada',
            name='iva_incluido',
        ),
        migrations.AddField(
            model_name='remito',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de IVA incluido'),
        ),
        migrations.AddField(
            model_name='remitoentrada',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de IVA incluido'),
        ),
    ]
