# Generated by Django 4.2.16 on 2026-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_change_iva_incluido_to_iva_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento sobre el precio de costo. Si es 0, usa el descuento general del proveedor.', max_digits=5, verbose_name='Descuento de proveedor (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento general que aplica el proveedor sobre el precio de costo.', max_digits=5, verbose_name='Descuento de compra (%)'),
        ),
    ]
