# Generated by Django 4.2.16 on 2026-09-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_add_supplier_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('category', 'Categoría'), ('brand', 'Marca')], default='category', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='category',
            name='external_code',
            field=models.CharField(blank=True, help_text='Código del rubro/marca en el sistema de gestión externo (Bejerman, Tango, etc.).', max_length=50, null=True, verbose_name='Código externo'),
        ),
        migrations.AddField(
            model_name='client',
            name='external_code',
            field=models.CharField(blank=True, help_text='Código del cliente en el sistema de gestión externo.', max_length=50, null=True, verbose_name='Código externo'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca del producto (categoría de tipo marca).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_brand', to='erp.category', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_code',
            field=models.CharField(blank=True, help_text='Código interno del producto en el sistema de gestión externo.', max_length=50, null=True, verbose_name='Código externo/SKU'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='external_code',
            field=models.CharField(blank=True, help_text='Código del proveedor en el sistema de gestión externo.', max_length=50, null=True, verbose_name='Código externo'),
        ),
    ]
